name: Build
on: [push]
jobs:
  no-libvarnish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo doc
  with-libvarnish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          set -x
          sudo apt-get install -y curl
          curl -s https://packagecloud.io/install/repositories/varnishcache/varnish75/script.deb.sh | sudo bash
          sudo apt-get install varnish-dev
      - run: |
          set -x
          cargo doc
          for dir in vmod_test $(ls -d examples/vmod_*); do
            (
              cd $dir
              cargo build --all-targets
              cargo test
            )
          done

